apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: f4kebmzyn-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/f4kebmzyn-java-springboot-gitops